server:
  port: 7002
spring:
  application:
    name: cloud-eureka-server
eureka:
  instance:
    hostname: eureka7002.com # eureka服务端的实例名称
  client:
    register-with-eureka: false # 不注册自己
    fetch-registry: false # 不发现服务
    service-url:
      # 设置与Eureka Server交互的地址查询服务和注册服务都需要这个地址
      defaultZone: http://eureka7001.com:7001/eureka
